$schema: http://json-schema.org/draft-07/schema#
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: API URL for InNoHassle Accounts
        title: Api Url
        type: string
      api_jwt_token:
        description: JWT token for accessing the Accounts API as a service
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  BotCommand:
    additionalProperties: true
    description: 'This object represents a bot command.


      Source: https://core.telegram.org/bots/api#botcommand'
    properties:
      command:
        title: Command
        type: string
      description:
        title: Description
        type: string
    required:
    - command
    - description
    title: BotCommand
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: $Schema
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  redis_url:
    anyOf:
    - format: password
      type: string
      writeOnly: true
    - type: 'null'
    default: null
    description: Redis URL
    examples:
    - redis://localhost:6379/0
    - redis://redis:6379/0
    title: Redis Url
  bot_token:
    description: Telegram bot token from @BotFather
    format: password
    title: Bot Token
    type: string
    writeOnly: true
  notification_bot_token:
    description: Telegram notification bot token from @BotFather
    format: password
    title: Notification Bot Token
    type: string
    writeOnly: true
  bot_name:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: Desired bot name
    title: Bot Name
  bot_description:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: Bot description
    title: Bot Description
  bot_short_description:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: Bot short description
    title: Bot Short Description
  bot_commands:
    anyOf:
    - items:
        $ref: '#/$defs/BotCommand'
      type: array
    - type: 'null'
    default: null
    description: Bot commands (displayed in telegram menu)
    title: Bot Commands
  admins:
    default: []
    description: Admin' telegram IDs
    items:
      type: integer
    title: Admins
    type: array
  accounts:
    anyOf:
    - $ref: '#/$defs/Accounts'
    - type: 'null'
    default: null
    description: Use production InNoHassle Accounts API for authentication in local
      development
  telegram_bind_url:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: URL for binding Telegram to InNoHassle Account
    title: Telegram Bind Url
  db_url:
    description: Connection String for SQLAlchemy
    examples:
    - postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/postgres
    - postgresql+asyncpg://postgres:postgres@db:5432/postgres
    format: password
    title: Db Url
    type: string
    writeOnly: true
  mock_auth:
    default: false
    description: Use MockAutoAuthMiddleware to bypass Authentication via InNoHassle
      Accounts (for testing)
    title: Mock Auth
    type: boolean
required:
- bot_token
- notification_bot_token
- db_url
title: Settings
type: object
