"""empty message

Revision ID: 61ec05663150
Revises: d4f7a9b2c311
Create Date: 2026-03-21 13:46:32.175546

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61ec05663150"
down_revision: str | None = "d4f7a9b2c311"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student", sa.Column("notification_bot_status", sa.SmallInteger(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student", "notification_bot_status")
    # ### end Alembic commands ###
