"""empty message

Revision ID: 2ee1d19f962d
Revises: 694dd524bb57
Create Date: 2026-04-05 15:57:00.925467

"""

# ruff: noqa: E501
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee1d19f962d"
down_revision: str | None = "694dd524bb57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("meeting_tutor_id_fkey"), "meeting", type_="foreignkey")
    op.create_foreign_key(None, "meeting", "tutor", ["tutor_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "meeting", type_="foreignkey")
    op.create_foreign_key(op.f("meeting_tutor_id_fkey"), "meeting", "tutor", ["tutor_id"], ["id"])
    # ### end Alembic commands ###
