"""initial

Revision ID: f008e211069e
Revises:
Create Date: 2026-03-07 15:40:39.142382

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f008e211069e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discipline",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_file_id", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=4096), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=36), nullable=True),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["email_id"], ["email.id"], onupdate="RESTRICT", ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receive_notifications", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student_discipline",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("discipline_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["discipline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "discipline_id"),
    )
    op.create_table(
        "tutor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(length=256), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("photo_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["student.id"],
        ),
        sa.ForeignKeyConstraint(["photo_id"], ["photo.id"], onupdate="CASCADE", ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meeting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("discipline_id", sa.Integer(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("room", sa.String(length=32), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("tutor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["student.id"],
        ),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["discipline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tutor_id"],
            ["tutor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tutor_discipline",
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        sa.Column("discipline_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["discipline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tutor_id"],
            ["tutor.id"],
        ),
        sa.PrimaryKeyConstraint("tutor_id", "discipline_id"),
    )
    op.create_table(
        "attendance",
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["email.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
        ),
        sa.PrimaryKeyConstraint("email_id", "meeting_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendance")
    op.drop_table("tutor_discipline")
    op.drop_table("meeting")
    op.drop_table("tutor")
    op.drop_table("student_discipline")
    op.drop_table("settings")
    op.drop_table("admin")
    op.drop_table("student")
    op.drop_table("photo")
    op.drop_table("email")
    op.drop_table("discipline")
    # ### end Alembic commands ###
