"""better foreign keys

Revision ID: b1b1734284a5
Revises: f008e211069e
Create Date: 2026-03-07 18:29:06.256514

"""

# ruff: noqa: E501
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1b1734284a5"
down_revision: str | None = "f008e211069e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("admin_id_fkey"), "admin", type_="foreignkey")
    op.create_foreign_key(None, "admin", "student", ["id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("attendance_meeting_id_fkey"), "attendance", type_="foreignkey")
    op.drop_constraint(op.f("attendance_email_id_fkey"), "attendance", type_="foreignkey")
    op.create_foreign_key(None, "attendance", "meeting", ["meeting_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "attendance", "email", ["email_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("meeting_discipline_id_fkey"), "meeting", type_="foreignkey")
    op.drop_constraint(op.f("meeting_creator_id_fkey"), "meeting", type_="foreignkey")
    op.create_foreign_key(None, "meeting", "discipline", ["discipline_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "meeting", "student", ["creator_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint(op.f("settings_id_fkey"), "settings", type_="foreignkey")
    op.create_foreign_key(None, "settings", "student", ["id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("student_discipline_student_id_fkey"), "student_discipline", type_="foreignkey")
    op.drop_constraint(op.f("student_discipline_discipline_id_fkey"), "student_discipline", type_="foreignkey")
    op.create_foreign_key(None, "student_discipline", "student", ["student_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "student_discipline", "discipline", ["discipline_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("tutor_id_fkey"), "tutor", type_="foreignkey")
    op.create_foreign_key(None, "tutor", "student", ["id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("tutor_discipline_tutor_id_fkey"), "tutor_discipline", type_="foreignkey")
    op.drop_constraint(op.f("tutor_discipline_discipline_id_fkey"), "tutor_discipline", type_="foreignkey")
    op.create_foreign_key(None, "tutor_discipline", "discipline", ["discipline_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "tutor_discipline", "tutor", ["tutor_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tutor_discipline", type_="foreignkey")
    op.drop_constraint(None, "tutor_discipline", type_="foreignkey")
    op.create_foreign_key(
        op.f("tutor_discipline_discipline_id_fkey"), "tutor_discipline", "discipline", ["discipline_id"], ["id"]
    )
    op.create_foreign_key(op.f("tutor_discipline_tutor_id_fkey"), "tutor_discipline", "tutor", ["tutor_id"], ["id"])
    op.drop_constraint(None, "tutor", type_="foreignkey")
    op.create_foreign_key(op.f("tutor_id_fkey"), "tutor", "student", ["id"], ["id"])
    op.drop_constraint(None, "student_discipline", type_="foreignkey")
    op.drop_constraint(None, "student_discipline", type_="foreignkey")
    op.create_foreign_key(
        op.f("student_discipline_discipline_id_fkey"), "student_discipline", "discipline", ["discipline_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("student_discipline_student_id_fkey"), "student_discipline", "student", ["student_id"], ["id"]
    )
    op.drop_constraint(None, "settings", type_="foreignkey")
    op.create_foreign_key(op.f("settings_id_fkey"), "settings", "student", ["id"], ["id"])
    op.drop_constraint(None, "meeting", type_="foreignkey")
    op.drop_constraint(None, "meeting", type_="foreignkey")
    op.create_foreign_key(op.f("meeting_creator_id_fkey"), "meeting", "student", ["creator_id"], ["id"])
    op.create_foreign_key(op.f("meeting_discipline_id_fkey"), "meeting", "discipline", ["discipline_id"], ["id"])
    op.drop_constraint(None, "attendance", type_="foreignkey")
    op.drop_constraint(None, "attendance", type_="foreignkey")
    op.create_foreign_key(op.f("attendance_email_id_fkey"), "attendance", "email", ["email_id"], ["id"])
    op.create_foreign_key(op.f("attendance_meeting_id_fkey"), "attendance", "meeting", ["meeting_id"], ["id"])
    op.drop_constraint(None, "admin", type_="foreignkey")
    op.create_foreign_key(op.f("admin_id_fkey"), "admin", "student", ["id"], ["id"])
    # ### end Alembic commands ###
