"""empty message

Revision ID: 886f61c9b850
Revises: 526260dce5bb
Create Date: 2026-04-04 17:51:07.591662

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "886f61c9b850"
down_revision: str | None = "526260dce5bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_update",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(length=32), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["meeting.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_update")
    # ### end Alembic commands ###
