"""empty message

Revision ID: 694dd524bb57
Revises: 886f61c9b850
Create Date: 2026-04-05 15:54:30.039077

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "694dd524bb57"
down_revision: str | None = "886f61c9b850"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meeting", "creator_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meeting", "creator_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
