"""empty message

Revision ID: 1050623cb411
Revises: 61ec05663150
Create Date: 2026-03-21 21:52:07.039689

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1050623cb411"
down_revision: str | None = "61ec05663150"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student", sa.Column("saw_guide", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student", "saw_guide")
    # ### end Alembic commands ###
