"""email not null

Revision ID: 7acee253eabe
Revises: b1b1734284a5
Create Date: 2026-03-09 12:25:04.145764

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7acee253eabe"
down_revision: str | None = "b1b1734284a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("email", "value", existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("email", "value", existing_type=sa.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###
