"""empty message

Revision ID: 526260dce5bb
Revises: 1050623cb411
Create Date: 2026-03-26 15:26:24.018389

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526260dce5bb"
down_revision: str | None = "1050623cb411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student", sa.Column("language", sa.String(length=2), server_default="en", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student", "language")
    # ### end Alembic commands ###
