INSERT INTO discipline (language, year, name) VALUES

('EN', 1, 'Data Structures and Algorithms'),
('EN', 1, 'Foreign Language'),
('EN', 1, 'Software System Analysis and Design'),
('EN', 1, 'Mathematical Analysis 2'),
('EN', 1, 'Theoretical Computer Science'),
('EN', 1, 'Analytical Geometry and Linear Algebra 2'),
('EN', 1, 'Software Engineering Toolkit'),

('EN', 2, 'System and Network Administration'),
('EN', 2, 'Theoretical Mechanics'),
('EN', 2, 'Human-AI Interaction Design'),
('EN', 2, 'Data Wrangling and Visualization'),
('EN', 2, 'Introduction to Machine Learning'),
('EN', 2, 'Networks'),
('EN', 2, 'Introduction to Game Development'),
('EN', 2, 'Fundamental of Robotics'),
('EN', 2, 'Databases'),
('EN', 2, 'Physics II'),
('EN', 2, 'Nature Inspired Computing'),
('EN', 2, 'Computer Graphics in Game Development'),
('EN', 2, 'Introduction to Control Systems Theory'),

('EN', 3, 'Software Quality Reliability and Security'),
('EN', 3, 'Generative AI'),
('EN', 3, 'Statistical Techniques'),
('EN', 3, 'Game Design and Interactive Narrative'),
('EN', 3, 'Secure System Development'),
('EN', 3, 'Natural Language Processing'),
('EN', 3, 'Sensors & Sensing'),
('EN', 3, 'Introduction to Big Data'),
('EN', 3, 'Lean Software Development'),
('EN', 3, 'Explainable and Fair AI'),
('EN', 3, 'Data Mining'),
('EN', 3, 'Artificial Intelligence in Games'),
('EN', 3, 'DevOps Engineering'),
('EN', 3, 'Advanced Linux'),
('EN', 3, 'Autonomous and Mobile Robotics'),

('RU', 1, 'Математический анализ'),
('RU', 1, 'Вычислительная линейная алгебра'),
('RU', 1, 'Иностранный язык'),
('RU', 1, 'Программирование на Python I'),
('RU', 1, 'Основы и методология программирования'),
('RU', 1, 'Общая физика'),
('RU', 1, 'Философия'),
('RU', 1, 'Алгоритмы и структуры данных'),
('RU', 1, 'Дискретная математика'),

('RU', 2, 'Теоретическая механика'),
('RU', 2, 'Теория случайный процессор'),
('RU', 2, 'Вычислительная математика'),
('RU', 2, 'Программирование на C++'),
('RU', 2, 'Современные численные методы оптимизации в обучении'),
('RU', 2, 'Машинное обучение'),
('RU', 2, 'Архитектура компьютера и операционные системы'),
('RU', 2, 'Математическая статистика ');
